apiVersion: apps/v1 
kind: Deployment
metadata:
  name: dns-watcher
  labels:
    app: dns-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-watcher
  template:
    metadata:
      labels:
        app: dns-watcher
    spec:
      containers:
      - name: dns-watcher
        image: registry.cn-beijing.aliyuncs.com/ringtail/dns-watcher:0.3
        